[project]
name = 'my-project'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = [
    { contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait' },
]

[contracts.nft-ticket]
path = 'contracts/nft-ticket.clar'
clarity_version = 3
epoch = 3.1

[contracts.nft-collectibles]
path = 'contracts/nft-collectibles.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
